FRONTENDSCHOOL5/final-10-Goodi

- src/style/GlobalStyle.jsx
#1 
GlobalStyle.css 에 기본 색상과 폰트 사이즈 변수 선언하였습니다.
body font-family를 프리텐다드로 설정해두었습니다.
> Style: Global style 색상, 폰트 변수 추가

- src/components/common/Card.jsx
- src/components/common/ProfileUI.jsx
- src/pages/Detail.jsx
- src/pages/Main.jsx
마크업, CSS 정리, main 비율 수정 하였습니다.
> Refactor: 마크업, CSS 정리 (#2)

- src/api/login.js
- src/components/common/ButtonLineIcon.jsx
- src/pages/Chat.jsx
- src/pages/Login.jsx
> Fix: 로그인 폼 예외처리 (#85)

- package-lock.json
- package.json
- src/index.js
- src/pages/Login.jsx
- src/pages/Main.jsx
- src/recoil/accountname.js
- src/recoil/loginCheck.js
- src/recoil/loginToken.js
로그인 상태 유지, 로그인 토큰 저장, accountname 로컬스토리지 저장
> feat: recoil 로컬스토리지 저장(#85)

- src/components/common/CardProduct.jsx
- src/pages/Profile.jsx
> Design: profile 페이지 레이아웃 변경-우측(#102)

- src/api/user.js
- src/pages/Join.jsx
- src/pages/Setprofile.jsx
서버에서 자동으로 처리해주는 오류는 잘 작동합니다.
이어서 오류 메세지 스타일링 작업예정입니다
> Feat: 회원가입 API 연동, 오류처리 완료, 상태에 따라 페이지 이동(#88)

- src/pages/Join.jsx
- src/pages/Setprofile.jsx
join 페이지에서는 API를 연결시키지 않아서 따로 유효성검사 부분 만들었습니다.
setprofile에서는 서버에서 쏴주는 유효성검사가 있어서 공백일 경우에만 오류로 띄워주게 해놨습니다.
> Feat: join, setprofile 오류 띄우는 기능 추가 및 스타일링 (#88)

- src/components/Follow.jsx
- src/components/common/CardProduct.jsx
- src/components/common/FollowBtn.jsx
- src/components/common/Post.jsx
- src/components/common/PostList.jsx
- src/pages/Profile.jsx
- 상품 목록, 게시물 목록 탭에 따른 컴포넌트 변경 처리
- 팔로워, 팔로잉 눌렀을 시 활성화 디자인
> Design: 유저 프로필 페이지 상세 수정

- src/api/follower.js
- src/api/following.js
- src/api/profile.js
- src/components/Follow.jsx
- src/components/common/ProfileUI.jsx
- src/pages/Profile.jsx
- 팔로워, 팔로잉 박스 클릭에 따른 사용자 프로필 목록 출력
- 표시해야할 사용자가 많을 시 예외 처리 필요
- 이슈 번호: #119
> Feat: 팔로워, 팔로잉 목록 연결(#119)

- src/api/UploadImage.js
- src/components/common/PostUI.jsx
- src/pages/PostProduct.jsx
- 상품 업로드 쪽 더미 데이터 연결 완료
- 이미지 3장 업로드 
<해결해야하는 오류>
- 이미지 교체하면 해당 인덱스로 교체
- 해당 타겟 이미지 교체
(각 input에 name 값을 줘서 해당 인덱스 값이 넘어오게 하려는 시도중)
<해야하는 것>
- PostUI 에 작성한 데이터 PostProduct에 전달
이슈번호: #121
> Feat: Image, product Post API 연동 및 token 연결(#121)

- src/api/UploadImage.js
- src/api/UploadProductAPI.js
- src/components/common/PostUI.jsx
- src/pages/PostProduct.jsx
<해야할 것>
- 이미지 중간에 수정하려고 할때 처리
- 작성중 나가려고 할때 처리(모달)
- 작성완료시 처리(모달)
- 업로드 완료시 해당 제품의 상세페이지로 이동
이슈번호: #121
> Feat: 이미지 여러장 상품 업로드 API 연결(#121)

- src/pages/Setprofile.jsx
- 프로필 이미지 업로드 기능 구현
- intro 업로드 기능 구현
- API 연동 완료
- profile 페이지에서 intro는 연동 되는데 프로필 이미지는 연동 안되는 문제 발견
> Feat: setprofile 프로필 이미지, intro 기능 구현, API 연동(#140)

- src/api/posting.js
- src/components/common/PostingUI.jsx
- src/pages/PostPosting.jsx
- src/pages/PostProduct.jsx
- postPosting과 postProduct에서 함께 사용하던 postUI 분리
- postingAPI에서 토큰 안불러와지는 문제 해결
- postingUI에서 textarea의 name을 link로 해놔서, API에 content가 아닌 link로 새롭게 들어가 게시글 내용이 적용안되는 문제 해결
> Feat: 게시글 작성 기능, content 연동, postUI 구분 (#126)

- src/api/follower.js
- src/components/common/PostList.jsx
- src/profileTest/FollowUI.jsx
- src/profileTest/IntroUI.jsx
- src/profileTest/ProfileLeftUI.jsx
- src/profileTest/ProfileRightUI.jsx
- src/profileTest/ProfileTest.jsx
- src/profileTest/UpdateProfile.jsx
프로필 페이지 컴포넌트 분리 작업 하였습니다.
- 이슈번호: #155
> Test: 프로필 페이지 컴포넌트 분리 테스트(#155)

- src/assets/icon_close.svg
- src/components/Navigation.jsx
- src/components/common/Search.jsx
- src/components/common/SearchHistory.jsx
- src/components/common/SearchInput.jsx
- src/components/common/SearchResult.jsx
- src/pages/Profile.jsx
- 네비게이션 검색 버튼 클릭시 모달 노출
- 모달 애니메이션
- 조건에 따른 스타일 구현
> Design: Search Modal 스타일 구현 완료(#152)

- src/api/likeBtn.js
- src/components/common/Post.jsx
- src/components/common/PostLikeBtn.jsx
- src/components/common/PostList.jsx
- src/pages/PostPosting.jsx
- hearted와 heartCount 상태는 유지되는데 새로고침하면 이미지가 초기화되는 문제
> Feat: 좋아요 API hearted, heartCount 연결(#126)

- src/components/common/PostList.jsx
- src/pages/profile/IntroUI.jsx
- src/pages/userProfile/UserProfile.jsx
- src/style/skeletonUI/SkeletonItem.jsx
- src/style/skeletonUI/skeletonPage/PostListSkeleton.jsx
> Design: 프로필 스켈레톤 UI 외 수정

- src/App.js
- src/components/common/Card.jsx
- src/components/common/Logout.jsx
- src/components/common/Post.jsx
- src/components/common/PostUI.jsx
- src/pages/Setprofile.jsx
- Feat: 로그인 라우트 path="/" 수정
- Fix: profileUI 상품, 게시물 컴포넌트에서 클릭 시 url undefined 변경 오류 수정
- Style: img 태그 alt 속성 추가
> Fix: 전체적인 세부 내용 수정

- src/components/common/Card.jsx
- src/components/common/Post.jsx
- src/pages/profile/IntroUI.jsx
- src/pages/profile/Profile.jsx
- 프로필, 상품, 게시글에 회원가입시 이미지 안들어오는 문제 해결 (BASE_URL 추가)
- 상품에 localNav 달기 위한 메뉴버튼 추가
> Feat: 프로필, 상품, 게시글 이미지, 상품 메뉴 추가(#190)

- src/api/productDelete.js
- src/api/productPut.js
- src/pages/Main.jsx
- src/style/skeletonUI/skeletonPage/MainSkeleton.jsx
main 페이지 스켈레톤 UI 구현
- 이슈번호: #177 
상품 수정, 삭제 API 생성
> Design: main 페이지 스켈레톤 UI 구현 외

- src/components/Navigation.jsx
- src/components/common/Card.jsx
- src/components/common/LocalNav.jsx
- src/components/common/Post.jsx
- main nav : 상품등록, 게시글 등록
- post : 게시글 수정, 게시글 삭제
- card : 상품 수정, 상품 삭제
> Feat: localNav 컴포넌트 페이지별 분기처리 및 띄움 (#190)

- src/components/common/Card.jsx
- src/components/common/Post.jsx
- lacalNav가 기존 컴포넌트에 영향을 주지 않기 위해 localNavWrap으로 감싸서 position 처리
> Design: card와 post에서 localNav의 위치 조정(#190)

- src/components/common/Card.jsx
- src/components/common/Post.jsx
- src/components/common/ProfileUI.jsx
- post의 mainprofile={false} 처리도 들어갔으니 mainprofile props로 스타일링시 참고해주세요
> Design: card, post 프로필 정보 부분 UI 수정 (#190)

- src/pages/profile/UpdateProfile.jsx
> Feat: 프로필 수정 시 post, card에서 이미지 리랜더링 처리(#190)

- src/App.js
- src/api/productDelete.js
- src/api/productPut.js
- src/components/common/Card.jsx
- src/components/common/CardProduct.jsx
- src/components/common/Modal.jsx
- src/components/common/UpdatePostUI.jsx
- src/pages/Detail.jsx
- src/pages/PostProduct.jsx
- src/pages/UpdateProduct.jsx
> Feat: 상품 수정, 삭제 기능

- src/components/common/PostingUI.jsx
- API에서 필수로 요구하는 데이터가 아니라서 글자수가 0이어도 상관 없음.
- 아예 게시글 내용 자체의 에러처리를 삭제
> Fix: post 등록시에 게시글 내용 오류 메세지 뜨는 에러 해결

- src/App.js
- src/assets/cart_null_icon.svg
- src/components/Header.jsx
- src/components/Navigation.jsx
- src/components/common/Count.jsx
- src/pages/Cart.jsx
- src/pages/Detail.jsx
- src/recoil/cartItemState.js
> Feat: Cart 페이지 마크업, 스타일링 구현, 왼쪽 영역 구현(#224)

- src/components/Navigation.jsx
- src/pages/Cart.jsx
- src/pages/Detail.jsx
> Feat: Cart 페이지 구현

- src/pages/UpdateProduct.jsx
- input 예외처리
- 로딩 시 걸어둔 div 삭제
> Fix: 상품 수정 페이지 부분 수정

- src/components/common/Logout.jsx
> Feat: 로그아웃시 장바구니 비우기(#236)

- src/components/Follow.jsx
- src/components/Navigation.jsx
- src/components/common/LikeBtn.jsx
- src/pages/Chat.jsx
- src/pages/profile/UpdateProfile.jsx
> Fix: 채팅, 프로필 세부 기능 수정(#236)

- src/components/common/MainRight.jsx
- src/pages/Main.jsx
메인에 있는 Card 선택시 해당 상품 상세페이지로 가지만, 프로필을 선택시 현재 로그인해있는 계정의 프로필로 가는 문제 있음
> Design: MainRight 목데이터처리 (#236)

- src/components/Navigation.jsx
- src/components/common/Card.jsx
- src/components/common/LocalNav.jsx
- src/components/common/MainRightCard.jsx
- src/components/common/Post.jsx
- src/components/common/ProfileUI.jsx
- src/pages/Main.jsx
> Fix: 로컬네비, main 상품 프로필 수정

- src/components/Footer.jsx
- src/components/common/MainRightCard.jsx
> Fix: main 상품 프로필 상세 버튼 숨김

- src/App.js
- react 특성상 사용하지 않는 컴포넌트도 매번 불러오기 때문에 성능에 많은 역할을 차지하는거같아 React.lazy로 필요할때만 불러올 컴포넌트 분활
...
> Refactor: React.lazy로 필요에 따라 import 해올 컴포넌트 분활 (#283)

- src/components/PostProductWriting/UIcomponents/ImageSection.jsx
- src/components/PostProductWriting/UIcomponents/PostWriting.jsx
- src/components/PostProductWriting/UIcomponents/ProductWriting.jsx
- src/components/PostProductWriting/UpdateTotalUI.jsx
- src/components/PostProductWriting/UploadTotalUI.jsx
- src/pages/PostUpload.jsx
- src/pages/ProductUpdate.jsx
- src/pages/ProductUpload.jsx
- 입력 폼 예외 처리도 업로드, 수정 부분 함께 쓸 수 있도록 합쳐졌습니다.
- 중복 코드 제거 작업
> Refactor: 상품, 게시물 등록/수정 예외 처리 추가
